#!/bin/sh
set -e

xhost +local:

USER="docker"
ROOTFS="$(readlink -f ./rootfs)"

pactl list | grep 'module-native-protocol-tcp' -A 1 | grep -q 'auth-ip-acl=127.0.0.1' || pactl load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
pactl list | grep -q 'module-x11-publish' || pactl load-module module-x11-publish

docker run -ti --rm \
       --name iceweasel \
       -e DISPLAY=${DISPLAY} \
       -v /dev/snd:/dev/snd \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v ${ROOTFS}/home/${USER}:/home/${USER} \
       --net=host \
       iceweasel /usr/bin/iceweasel --private-window > /dev/null

xhost -local:
