#!/bin/sh
set -e

# Change Working Directory
cd "$(dirname $(readlink -f $0))"

[ -z "${UID}" ] && UID="$(id -u)"
[ -z "${GID}" ] && GID="$(id -g)"

# Build container
CONTAINER="${PWD##*/}"
docker build --build-arg UID=${UID} --build-arg GID=${GID} -t ${CONTAINER} .
