#!/bin/sh
set -e

mkdir -pv ./rootfs/home/docker

# Build container
CONTAINER="${PWD##*/}"

USER="docker"
ROOTFS="$(readlink -f ./rootfs)"

docker run -ti --rm \
       --name ${CONTAINER} \
       --net=host \
       -v ${ROOTFS}/home/${USER}:/home/${USER} \
       ${CONTAINER} /bin/bash
