#!/bin/sh
set -ex

# Change directory to script directory
cd "$(dirname $(readlink -f $0))"

[ -z "${UID}" ] && UID="$(id -u)"
[ -z "${GID}" ] && GID="$(id -g)"

# Build container
docker build --build-arg UID=${UID} --build-arg GID=${GID} -t local/aurora .

mkdir -pv ./rootfs/home/docker

# Change directory to previous directory
cd ${OLDPWD}
