#!/bin/sh
set -e

xhost +local:

USER="docker"
ROOTFS="$(readlink -f ./rootfs)"

docker run -ti --rm \
       --name firefox \
       -e DISPLAY=${DISPLAY} \
       -e XMODIFIERS="@im=fcitx" \
       -e GTK_IM_MODULE=fcitx \
       -e QT_IM_MODULE=fcitx \
       -e XIMPROGRAM=fcitx \
       -e LC_CTYPE=ja_JP.UTF-8 \
       --device /dev/snd \
       --device /dev/dri \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v ${ROOTFS}/home/${USER}:/home/${USER} \
       --net=host \
       firefox /usr/bin/firefox --private-window

xhost -local:
