#!/bin/sh
set -eu

xhost +local:

USER="docker"
ROOTFS="$(readlink -f ./rootfs)"

docker run -ti --rm \
       --name firefox \
       -e DISPLAY=${DISPLAY} \
       -e XMODIFIERS="@im=fcitx" \
       -e GTK_IM_MODULE=fcitx \
       -e QT_IM_MODULE=fcitx \
       -e XIMPROGRAM=fcitx \
       -e LC_CTYPE=ja_JP.UTF-8 \
       --device /dev/dri \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /run/user/1000/pulse:/run/pulse \
       -v ${ROOTFS}/home/${USER}:/home/${USER} \
       --ipc=host \
       --net=host \
       firefox /usr/bin/firefox --private-window
       # firefox /bin/bash

xhost -local:
