#!/bin/sh
set -e

# Change working directory
cd "$(dirname $(readlink -f $0))"

[ -z "${UID}" ] && UID="$(id -u)"
[ -z "${GID}" ] && GID="$(id -g)"

docker build --pull --build-arg UID=${UID} --build-arg GID=${GID} -t scrcpy .
