#!/bin/sh
set -eu

xhost +local:

USER="docker"
HOME="$(readlink -f ./docker)"

docker run -ti --rm \
       --name wine \
       -e DISPLAY=${DISPLAY} \
       -e XMODIFIERS="@im=fcitx" \
       -e GTK_IM_MODULE=fcitx \
       -e QT_IM_MODULE=fcitx \
       -e XIMPROGRAM=fcitx \
       -e LC_CTYPE=ja_JP.UTF-8 \
       -e WINEARCH="win64" \
       --device /dev/dri \
       --device /dev/video0 \
       -v /var/run/cups:/var/run/cups \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /run/user/1000/pulse:/run/pulse \
       -v ${HOME}:/home/${USER} \
       --ipc=host \
       --net=host \
       wine /bin/bash

xhost -local:

## Zwift setup installation
# apt-get purge -yq mono-complete
# winetricks dotnet35sp1 win7
# wine ./ZwiftSetup.exe
# cd ./.wine/drive_c/Program\ Files\ \(x86\)/Zwift
# wine ./ZwiftLauncher.exe

## Kindle setup
# winetricks kindle
# wine ./.wine/drive_c/Program\ Files/Amazon/Kindle/Kindle.exe

## Remove .wine & Setup .wine
# rm -rfv ./.wine
# winetricks corefonts cjkfonts
# regedit logpixels.reg
